full_stack_test/event_scheduler/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

root "homepages#new"

get 'event/new' => "events#new", :as => "event"
get 'event/list' => "events#index", :as => "event_list"
get 'newform/new' => "events#newform", :as => "newform"
post 'newform/new' => "events#create", :as => 'create_eventform'
get 'event/:id/edit' => "events#edit", :as => 'edit_event'
put 'event/:id/edit' => "events#update", :as => "update_event"

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
resources :users
resources :sessionss

end

full_stack_test/event_scheduler/app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :owner,class_name: "User"
	has_many :invitees, :through => :invitations, foreign_key: :invitee_id
	has_many :invitations
end

full_stack_test/event_scheduler/app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :event
	belongs_to :invitee, class_name: "User"
	# belongs_to :inviter, class_name: "User"
end

full_stack_test/event_scheduler/app/models/user.rb
class User < ActiveRecord::Base
	# attr_accessible :email, :password, :password_confirmation
  has_many :events, foreign_key: :owner_id
  # has_many :invitations, foreign_key: :invitee_id
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates :password,:length => {:within => 8..40}
  validates_uniqueness_of :email
  
  PASSWORD_FORMAT = /\A
 (?=.{8,})          # Must contain 8 or more characters
 (?=.*\d)           # Must contain a digit
 (?=.*[a-z])        # Must contain a lower case character
 (?=.*[A-Z])        # Must contain an upper case character
 (?=.*[[:^alnum:]]) # Must contain a symbol
/x
validates :password,
 format: {with: PASSWORD_FORMAT}
 
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

full_stack_test/event_scheduler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

full_stack_test/event_scheduler/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :find_id
	def new
		@event=Event.new

	end

	def newform
		@event=Event.new
		@users=User.all
	end

	def index
		@events=Event.all
		@users=User.all
	end

	def create
		
		current_user.events << Event.new(event_params)      # Event.last.owner=current_user
         
         current_user.events.last.invitees << User.find(params["invitee_ids"])
        
       redirect_to event_list_path
	end

	def edit
		@event_edit=@event.id
		@users=User.all
	end

	def update
		# @event=Event.find_by_id(params[:id])
		@event.update_attributes(event_params)
		redirect_to event_list_path
	end

	private
	def event_params
		params.require(:event).permit(:eventtitle,:venue,:date,:time,:description,:invitees,:status)
	end

	def find_id
		@event=Event.find_by_id(params[:id])
	end
end

full_stack_test/event_scheduler/app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
end

full_stack_test/event_scheduler/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
    	session[:user_id] = user.id
    	redirect_to event_path, :notice => "Logged in!"
  	else
    	flash.now.alert = "Invalid email or password"
    	render "new"
  	end
	end

	def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => "Logged out!"
	end
end

full_stack_test/event_scheduler/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			redirect_to log_in_path,:notice => "Signed up"
		else
			render "new"
		end
	end

	private
	def user_params
		params.require(:user).permit(:firstname,:lastname,:username,:email,:phonenumber,:password,:password_confirmation)
	end
end

full_stack_test/event_scheduler/app/helpers/application_helper.rb
module ApplicationHelper
end

full_stack_test/event_scheduler/app/helpers/events_helper.rb
module EventsHelper
end

full_stack_test/event_scheduler/app/helpers/homeindex_helper.rb
module HomeindexHelper
end

full_stack_test/event_scheduler/app/helpers/homepages_helper.rb
module HomepagesHelper
end

full_stack_test/event_scheduler/app/helpers/sessions_helper.rb
module SessionsHelper
end

full_stack_test/event_scheduler/app/helpers/users_helper.rb
module UsersHelper
end

full_stack_test/event_scheduler/app/views/events/edit.html.erb
<div class="form">
<% if current_user.id==@event.owner_id %>
<%= form_for :event,url:update_event_path,method: :put do |f| %>
<p>
  <%= f.label :Eventtitle %><br/>
  <%= f.text_field :eventtitle %>  
</p>
<p>        
  <%= f.label :Venue %><br/>
  <%= f.text_field :venue %>
</p>
<p>
<%= f.label :Date %>
<div class="datetime_select">
     <%= select_month Time.now, prefix: :event,
                                field_name: :"event_date(2i)"
                                 %> /
     <%= select_day Time.now, prefix: :event,
                              field_name: :"event_date(3i)"
                               %> /
     <%= select_year Time.now, prefix: :event,
                               field_name: :"event_date(1i)",
                               start_year: Time.now.year - 1
                                %>
</div></p>
<p>
  <%= f.label :Time %>
   <div class="datetime_select">
   <%= select_hour 12, prefix: :event,
                               field_name: :"event_date(4i)",
                               ampm: true
                                %> :
     <%= select_minute 0, prefix: :event,
                                 field_name: :"event_date(5i)"
                                 %>
    </div></p>

<p>      
  <%= f.label :Description %><br/>
  <%= f.text_area :description, size: "20x3" %>
</p>
<p>
  <%= f.label :Invitees %><br />

  <ul>
 <% @users.each do |role| %>
   <li>
     <%= check_box_tag 'invitee_ids[]', role.id -%>
     <%= role.username -%>
   </li>
 <% end %>
</ul>
<p>
    <%= f.label :status %><br />
    <%= f.select :status, ['open', 'closed']%>
  </p>
</p>
   <%= f.submit "Create event" %>
 <% end %>
 <% else %>
 <%= form_for :event,url:update_event_path,method: :put do |f| %>
<p>
  <%= f.label :Eventtitle %><br/>
  <%= f.text_field :eventtitle,:disabled=>true %>  
</p>
<p>        
  <%= f.label :Venue %><br/>
  <%= f.text_field :venue,:disabled=>true %>
</p>
<p>
<%= f.label :Date %>
<div class="datetime_select">
     <%= select_month Time.now, prefix: :event,
                                field_name: :"event_date(2i)"
                                 %> /
     <%= select_day Time.now, prefix: :event,
                              field_name: :"event_date(3i)"
                               %> /
     <%= select_year Time.now, prefix: :event,
                               field_name: :"event_date(1i)",
                               start_year: Time.now.year - 1
                                %>
</div></p>
<p>
  <%= f.label :Time %>
   <div class="datetime_select">
   <%= select_hour 12, prefix: :event,
                               field_name: :"event_date(4i)",
                               ampm: true
                                %> :
     <%= select_minute 0, prefix: :event,
                                 field_name: :"event_date(5i)"
                                 %>
    </div></p>

<p>      
  <%= f.label :Description %><br/>
  <%= f.text_area :description, size: "20x3",:disabled=>true %>
</p>
<p>
  <%= f.label :Invitees %><br />

  <ul>
 <% @users.each do |role| %>
   <li>
     <%= check_box_tag 'invitee_ids[]', role.id,:disabled=>true -%>
     <%= role.username -%>
   </li>
 <% end %>
</ul>
</p>
<p>
    <%= f.label :status %><br />
    <%= f.select :status, ['open', 'closed'],:disabled=>true%>
  </p>

   <%= f.submit "Create event" %>
 <% end %>
  <% end %>
</div>

full_stack_test/event_scheduler/app/views/events/index.html.erb
<meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<%= link_to 'Create new events', newform_path, :class => "btn-warning" %>
<div class="row">
  <div class="col-xs-6">
    <% @events.each do |event| %>    
    <div class="row" style="background-color:#D3D3D3; margin:5px;padding:20px">
   <label style="color:green">Event:</label><label> <%= event.eventtitle %></label><br>
   
   <label style="color:green">Venue: </label><label><%= event.venue %></label>        <div class="container">
<%= link_to 'Edit event', edit_event_path(event) %>
<!-- Trigger the modal with a button -->
<a  data-toggle="modal" data-target="#myModal2-<%= event.id %>">Participants</a> <!-- Modal -->
<div class="modal fade" id="myModal2-<%= event.id %>" role="dialog">
  <div class="modal-dialog">
 
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">List of Participants</h4>
      </div>
      <div class="modal-body">
        <% event.invitees.each do |user| %>
 
    <p><%= user.firstname %></p>
  <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
   
  </div>
</div>

</div>    </div>
<% end %></div>
<div class="col-xs-6">
   
   </div></div>

full_stack_test/event_scheduler/app/views/events/new.html.erb
<%= link_to 'Create new events', newform_path, :class => "btn-warning" %>

full_stack_test/event_scheduler/app/views/events/newform.html.erb
<div class="form">
<%= form_for :event do |f| %>
<p>
  <%= f.label :Eventtitle %><br/>
  <%= f.text_field :eventtitle %>  
</p>
<p>        
  <%= f.label :Venue %><br/>
  <%= f.text_field :venue %>
</p>
<p>
<%= f.label :Date %>
<div class="datetime_select">
     <%= select_month Time.now, prefix: :event,
                                field_name: :"event_date(2i)"
                                 %> /
     <%= select_day Time.now, prefix: :event,
                              field_name: :"event_date(3i)"
                               %> /
     <%= select_year Time.now, prefix: :event,
                               field_name: :"event_date(1i)",
                               start_year: Time.now.year - 1
                                %>
</div></p>
<p>
  <%= f.label :Time %>
   <div class="datetime_select">
   <%= select_hour 12, prefix: :event,
                               field_name: :"event_date(4i)",
                               ampm: true
                                %> :
     <%= select_minute 0, prefix: :event,
                                 field_name: :"event_date(5i)"
                                 %>
    </div></p>

<p>      
  <%= f.label :Description %><br/>
  <%= f.text_area :description, size: "20x3" %>
</p>
<p>
  <%= f.label :Invitees %><br />

  <ul>
 <% @users.each do |role| %>
   <li>
     <%= check_box_tag 'invitee_ids[]', role.id -%>
     <%= role.username -%>
   </li>
 <% end %>
</ul>
<p>
    <%= f.label :status %><br />
    <%= f.select :status, ['open', 'closed']%>
  </p>
</p>
   <%= f.submit "Create event" %>
 <% end %>
</div>

full_stack_test/event_scheduler/app/views/homepages/new.html.erb
 <div class="box">
  <h3>EVENT SCHEDULER PROJECT</h3>
  <p class="lead">Designed by-Meghavi</p>
</div>

full_stack_test/event_scheduler/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventScheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<h1>EVENT SCHEDULER</h1>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.username %>.
    <%= link_to '<button type="button">Log Out</button>'.html_safe, log_out_path %> 
  <% else %>
    <%= link_to '<button type="button">Sign Up</button>'.html_safe, sign_up_path %> 
   <%= link_to '<button type="button">Log In</button>'.html_safe, log_in_path %> 
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</header>


<%= yield %>
<footer class="footer">
      <p>Copyright &copy;2016 - Designed by Meghavi</p>
     
</footer>


</body>
</html>

full_stack_test/event_scheduler/app/views/users/new.html.erb
<div class="form">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname,:required => true %>
  </p>
  <p>
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname,:required => true %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username,:required => true %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email,:required => true %>
  </p>
  <p>
    <%= f.label :phonenumber %><br />
    <%= f.telephone_field :phonenumber,:required => true,:maxlength=>"10" %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= submit_tag "Register" %>
  <%= submit_tag "cancel" %></p>
<% end %>
</div>